
root_dir: "../"
data_directory: "nyc_taxi_trip_duration/split/"
train_dataset: "train.csv"
val_dataset: "val.csv"
#drop_cols: ["id", "dropoff_datetime", "passenger_count", "pickup_longitude", "pickup_latitude", "dropoff_longitude", "dropoff_latitude"]
drop_cols: ["id", "dropoff_datetime"]
datetime_cols: 'pickup_datetime'
target_col: "trip_duration"
scaler: sklearn.preprocessing.MinMaxScaler()
#  minmax: MinMaxScaler()
#  stand: StandardScaler()
encoder: OneHotEncoder()
encode_cols: ['store_and_fwd_flag']
model: LinearRegression
metric: r2_score
